## Read CSV

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

# Load the dataset from Google Drive, specifying a different encoding
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/divar_ads_full.csv', encoding='utf-8')

/tmp/ipykernel_21030/2387117821.py:4: DtypeWarning: Columns (33,34,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/divar_ads_full.csv', encoding='utf-8')

## Data Loading and Initial Inspection

In [ ]:
# Display the shape of the DataFrame
print(f"Shape of the DataFrame: {df.shape}")

Shape of the DataFrame: (24537, 49)

In [ ]:
# Display the first 5 rows of the DataFrame
print("First 5 rows of the DataFrame:")
display(df.head())

First 5 rows of the DataFrame:

,ردیف,کلید,لینک,اسکریپ جزییات,عنوان,قیمت,آدرس,دسته بندی,زمان و مکان,ویژگی ها,...,پیش پرداخت اولیه,پرداختی در زمان تحویل,تأیید حضوری در تاریخ,تحویل,اطلاعات هویتی,مالکیت موبایل,مطابقت چهره,تعداد اتاق,شروع قیمت,زمان خاتمه
0,1,QaxPhWrT,https://divar.ir/v/%D9%81%D8%B1%D9%88%D8%B4-%D...,اسکریپ شد,میمه باغ ویلا دو قطعه فول امکانات,"۷,۵۰۰,۰۰۰,۰۰۰ تومان",۱ هفته پیش در میمه، جاده میمه - کاشان,املاک > فروش مسکونی > فروش خانه و ویلا > میمه ...,NaN,پارکینگ، انباری,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Qa1uXOUj,https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9...,اسکریپ شد,اجاره ویلا باغبادران باغبهادران استخر ابگرم شیک,NaN,۷ هفته پیش در باغ بهادران، خ وشمندجان,املاک > اجارهٔ کوتاه‌مدت > اجارهٔ کوتاه‌مدت وی...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Qa7rwKxA,https://divar.ir/v/%D9%81%D8%B1%D9%88%D8%B4-%D...,اسکریپ شد,فروش زمین باغ خوش جا,"۱,۵۰۰,۰۰۰ تومان",۲ روز پیش در خمینی‌شهر، خ انقلاب,املاک > فروش مسکونی > فروش زمین و ملک کلنگی > ...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,QaunBaar,https://divar.ir/v/%D8%B2%D9%85%DB%8C%D9%86-%D...,اسکریپ شد,زمین چسبیده به بافت مسکونی شاهین شهر سند تک برگ,"۵۰,۰۰۰,۰۰۰ تومان",۱ هفته پیش در شاهین‌شهر، عطار، خ مولوی,املاک > فروش مسکونی > فروش زمین و ملک کلنگی > ...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Qa7nA936,https://divar.ir/v/%D9%85%D9%86%D8%B2%D9%84-%D...,اسکریپ شد,منزل فروشی در نوش آباد,"۵,۰۰۰,۰۰۰,۰۰۰ تومان",۲ روز پیش در آران و بیدگل، خ امام خمینی,املاک > فروش مسکونی > فروش خانه و ویلا > منزل ...,NaN,پارکینگ، انباری,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Calculate the percentage of missing values for each column in df
missing_percentage = df.isnull().sum() * 100 / len(df)
missing_percentage = missing_percentage.sort_values(ascending=False)

print("Percentage of missing values per column in df_cleaned:")
print(missing_percentage[missing_percentage > 90])

Percentage of missing values per column in df_cleaned:
زمان و مکان                   100.000000
آدرس عکس ها                   100.000000
پوشه عکس ها                   100.000000
زمان خاتمه                     99.995925
شروع قیمت                      99.995925
وضعیت                          99.995925
تاریخ استعلام                  99.995925
تعداد اتاق                     99.987774
اطلاعات هویتی                  99.955170
مطابقت چهره                    99.955170
مالکیت موبایل                  99.955170
تأیید حضوری در تاریخ           99.922566
پیشرفت فیزیکی کل پروژه         99.804377
تحویل                          99.796226
سازنده                         99.702490
پرداختی در زمان تحویل          99.592452
پیش پرداخت اولیه               99.515018
کمترین متراژ                   99.494641
وضعیت فعلی پروژه               99.409056
قیمت پایه برای هر متر مربع     99.327546
نوع واحد‌ها                    99.148225
تعطیلات و مناسبت‌ها            93.801198
هزینهٔ هر نفرِ اضافه           93.801198
آخر هفته                       93.801198
روزهای عادی                    93.801198
ظرفیت                          93.760443
dtype: float64

In [ ]:
# List of columns to drop based on their apparent relevance to house price estimation
columns_to_drop_initial = [
    'ردیف',
    'کلید',
    'لینک',
    'توضیحات',
    'زمان و مکان',
    'آخر هفته',
    'روزهای عادی',
    'زمان خاتمه',
    'سازنده',
    'شروع قیمت',
    'ظرفیت',
    'کمترین متراژ',
    'هزینهٔ هر نفرِ اضافه',
    'تعطیلات و مناسبت‌ها',
    'تعداد عکس',
    'پوشه عکس‌ها',
    'آدرس عکس‌ها',
    'تصویر نقشه',
    'تصویر‌ها برای همین ملک است؟',
    'اسکریپ جزییات',
    'پوشه عکس ها',
    'آدرس عکس ها',
    'تأیید حضوری در تاریخ',
    'اطلاعات هویتی',
    'مالکیت موبایل',
    'مطابقت چهره',
    # Columns with missvaluerate higher than 90%
    'پیشرفت فیزیکی کل پروژه',
    'تحویل',
    'پرداختی در زمان تحویل',
    'پیش پرداخت اولیه',
    'وضعیت فعلی پروژه',
    'قیمت پایه برای هر متر مربع',
    'نوع واحد‌ها',
    'تاریخ استعلام',
    'وضعیت',
    'قیمت',
    'تعداد اتاق',
]

df_cleaned = df.drop(columns=columns_to_drop_initial, errors='ignore')

print(f"Shape of DataFrame after dropping columns with >90% missing values: {df_cleaned.shape}")
print("Remaining columns after this step:")
print(df_cleaned.shape)

Shape of DataFrame after dropping columns with >90% missing values: (24537, 15)
Remaining columns after this step:
(24537, 15)

In [ ]:
print("Remaining columns after this step:")
print(df_cleaned.columns)

Remaining columns after this step:
Index(['عنوان', 'آدرس', 'دسته بندی', 'ویژگی ها', 'توضیحات کامل', 'متراژ',
       'ساخت', 'اتاق', 'متراژ زمین', 'قیمت کل', 'قیمت هر متر', 'ودیعه',
       'اجارهٔ ماهانه', 'ودیعه و اجاره', 'طبقه'],
      dtype='object')

## Data Cleaning and Preprocessing - Renaming and Type Conversion

Rename persian to english words

In [ ]:
column_rename_map = {
    'عنوان': 'title',
    'دسته بندی': 'category',
    'توضیحات کامل': 'description',
    'اتاق': 'rooms',
    'اجارهٔ ماهانه': 'monthly_rent',
    'طبقه': 'floor',
    'قیمت کل': 'total_price',
    'قیمت هر متر': 'price_per_meter',
    'متراژ': 'area',
    'متراژ زمین': 'land_area',
    'ودیعه': 'deposit',
    'ودیعه و اجاره': 'deposit_and_rent_type',
    'ویژگی ها': 'features',
    'زمین': 'land',
    'ویلا': 'villa',
    'آپارتمان': 'apartment',
    'مغازه': 'shop',
    'تجاری': 'commercial',
    'ساخت': 'builded_date',
    'آدرس': 'location'
}

df_cleaned = df_cleaned.rename(columns=column_rename_map)

print("DataFrame columns after renaming to English:")
display(df_cleaned.head())

DataFrame columns after renaming to English:

,title,location,category,features,description,area,builded_date,rooms,land_area,total_price,price_per_meter,deposit,monthly_rent,deposit_and_rent_type,floor
0,میمه باغ ویلا دو قطعه فول امکانات,۱ هفته پیش در میمه، جاده میمه - کاشان,املاک > فروش مسکونی > فروش خانه و ویلا > میمه ...,پارکینگ، انباری,⚜️ مشخصات کلی و امکانات\n* ۳۰۰۰ متر باغ ویلا، ...,۷۵,۱۴۰۰,۱,۳۰۰۰,"۷,۵۰۰,۰۰۰,۰۰۰ تومان","۲,۵۰۰,۰۰۰ تومان",NaN,NaN,NaN,NaN
1,اجاره ویلا باغبادران باغبهادران استخر ابگرم شیک,۷ هفته پیش در باغ بهادران، خ وشمندجان,املاک > اجارهٔ کوتاه‌مدت > اجارهٔ کوتاه‌مدت وی...,NaN,کد 109\nدو خواب استخر سرپوشیده آبگرم \nبا تصفی...,۷۰۰,NaN,۲,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,فروش زمین باغ خوش جا,۲ روز پیش در خمینی‌شهر، خ انقلاب,املاک > فروش مسکونی > فروش زمین و ملک کلنگی > ...,NaN,✅زمین باغ آجیلی ✅ \nیک جریب و نیم ابعاد 15=100...,۵۰۰ متر,NaN,NaN,NaN,"۱,۵۰۰,۰۰۰ تومان","۳,۰۰۰ تومان",NaN,NaN,NaN,NaN
3,زمین چسبیده به بافت مسکونی شاهین شهر سند تک برگ,۱ هفته پیش در شاهین‌شهر، عطار، خ مولوی,املاک > فروش مسکونی > فروش زمین و ملک کلنگی > ...,NaN,زمین مشاع( تفکیک نشده)\nجهت سرمایه گذاری\nسند ...,۲۰۰ متر,NaN,NaN,NaN,"۵۰,۰۰۰,۰۰۰ تومان","۲۵۰,۰۰۰ تومان",NaN,NaN,NaN,NaN
4,منزل فروشی در نوش آباد,۲ روز پیش در آران و بیدگل، خ امام خمینی,املاک > فروش مسکونی > فروش خانه و ویلا > منزل ...,پارکینگ، انباری,منزل دو طبقه فروشی\nقیمت کارشناسی باید بشه,۱,۱۳۹۵,۲,۲۶۶,"۵,۰۰۰,۰۰۰,۰۰۰ تومان","۱۸,۷۹۶,۰۰۰ تومان",NaN,NaN,NaN,NaN

In [ ]:
def persian_to_english_numerals(text):
    if pd.isna(text) or not isinstance(text, str):
        return text
    persian_to_english_map = {
        '۰': '0', '۱': '1', '۲': '2', '۳': '3', '۴': '4',
        '۵': '5', '۶': '6', '۷': '7', '۸': '8', '۹': '9'
    }
    translated_text = ''.join([persian_to_english_map.get(char, char) for char in text])
    return translated_text

In [ ]:
def clean_and_convert_numeric_column(df, column_name):
    if column_name in df.columns:
        # Ensure the column is string type for processing
        df[column_name] = df[column_name].astype(str)
        # Apply Persian to English numeral conversion using the existing function
        df[column_name] = df[column_name].apply(persian_to_english_numerals)
        # Remove non-numeric characters (e.g., 'تومان', 'متر', commas, spaces) but keep dots for decimals
        df[column_name] = df[column_name].str.replace(r'[^۰-۹0-9.]', '', regex=True)
        # Convert to numeric, coercing errors to NaN
        df[column_name] = pd.to_numeric(df[column_name], errors='coerce')
    return df

# List of columns to clean and convert
columns_to_process = [
    'monthly_rent',
    'floor',
    'total_price',
    'price_per_meter',
    'area',
    'land_area',
    'deposit',
    'rooms',
    'builded_date'
]

# Apply the cleaning and conversion to each specified column
for col in columns_to_process:
    df_cleaned = clean_and_convert_numeric_column(df_cleaned, col)

print("DataFrame after converting Persian numerals and cleaning numeric columns:")
display(df_cleaned.head())

DataFrame after converting Persian numerals and cleaning numeric columns:

,title,location,category,features,description,area,builded_date,rooms,land_area,total_price,price_per_meter,deposit,monthly_rent,deposit_and_rent_type,floor
0,میمه باغ ویلا دو قطعه فول امکانات,۱ هفته پیش در میمه، جاده میمه - کاشان,املاک > فروش مسکونی > فروش خانه و ویلا > میمه ...,پارکینگ، انباری,⚜️ مشخصات کلی و امکانات\n* ۳۰۰۰ متر باغ ویلا، ...,75.0,1400.0,1.0,3000.0,7.500000e+09,2500000.0,NaN,NaN,NaN,NaN
1,اجاره ویلا باغبادران باغبهادران استخر ابگرم شیک,۷ هفته پیش در باغ بهادران، خ وشمندجان,املاک > اجارهٔ کوتاه‌مدت > اجارهٔ کوتاه‌مدت وی...,NaN,کد 109\nدو خواب استخر سرپوشیده آبگرم \nبا تصفی...,700.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,فروش زمین باغ خوش جا,۲ روز پیش در خمینی‌شهر، خ انقلاب,املاک > فروش مسکونی > فروش زمین و ملک کلنگی > ...,NaN,✅زمین باغ آجیلی ✅ \nیک جریب و نیم ابعاد 15=100...,500.0,NaN,NaN,NaN,1.500000e+06,3000.0,NaN,NaN,NaN,NaN
3,زمین چسبیده به بافت مسکونی شاهین شهر سند تک برگ,۱ هفته پیش در شاهین‌شهر، عطار، خ مولوی,املاک > فروش مسکونی > فروش زمین و ملک کلنگی > ...,NaN,زمین مشاع( تفکیک نشده)\nجهت سرمایه گذاری\nسند ...,200.0,NaN,NaN,NaN,5.000000e+07,250000.0,NaN,NaN,NaN,NaN
4,منزل فروشی در نوش آباد,۲ روز پیش در آران و بیدگل، خ امام خمینی,املاک > فروش مسکونی > فروش خانه و ویلا > منزل ...,پارکینگ، انباری,منزل دو طبقه فروشی\nقیمت کارشناسی باید بشه,1.0,1395.0,2.0,266.0,5.000000e+09,18796000.0,NaN,NaN,NaN,NaN

## Feature Engineering - Property Type One-Hot Encoding

In [ ]:
# Create new columns for one-hot encoding, initialized to 0
df_cleaned['apartment'] = 0

# Helper function to get the nth part of a category string
def get_category_part(category_string, part_index):
    if pd.isna(category_string):
        return None
    parts = category_string.split('>')
    if len(parts) > part_index:
        return parts[part_index].strip()
    return None

# Extract the third part of the category for all rows
df_cleaned['category_third_part'] = df_cleaned['category'].apply(lambda x: get_category_part(x, 2))

# Apply the logic based on the third part of the category

# Apartment: Check for 'آپارتمان' in the third part
df_cleaned.loc[df_cleaned['category_third_part'].str.contains('فروش آپارتمان', na=False, case=False), 'apartment'] = 1

# Drop the temporary category_third_part column
df_cleaned = df_cleaned.drop(columns=['category_third_part'])

print("DataFrame with updated one-hot encoded columns based on third part of category:")
print(df_cleaned.shape)

DataFrame with updated one-hot encoded columns based on third part of category:
(24537, 16)

## Data Filtering - Removing Uncategorized Rows

Remove trash rows

In [ ]:
empty_keyword_rows = df_cleaned[(df_cleaned['apartment'] == 0)]

print(f"Number of rows where 'زمین', 'ویلا', and 'آپارتمان' are all empty: {len(empty_keyword_rows)}")

Number of rows where 'زمین', 'ویلا', and 'آپارتمان' are all empty: 20784

In [ ]:
df_cleaned = df_cleaned[~(df_cleaned['apartment'] == 0)]

print(f"Shape of DataFrame after removing rows with no assigned keyword: {df_cleaned.shape}")

Shape of DataFrame after removing rows with no assigned keyword: (3753, 16)

## Handling Missing Values - Rooms and Floor

Fill NaN values of rooms and floor

In [ ]:
df_cleaned["rooms_missing"] = df_cleaned["rooms"].isna().astype(int)
df_cleaned.loc[df_cleaned["rooms_missing"] == 1, "rooms"] = -1

df_cleaned["floor_missing"] = df_cleaned["floor"].isna().astype(int)
df_cleaned.loc[df_cleaned["floor_missing"] == 1, "floor"] = -1

## Extract description data

### Extract parking, elevator, storage datas for one-hot encoding

In [ ]:
# Create new columns for the requested features and initialize to 0
df_cleaned['parking'] = 0
df_cleaned['elevator'] = 0
df_cleaned['storage'] = 0

# Check if 'features' column exists before processing
if 'features' in df_cleaned.columns:
    # Convert 'features' column to string and fill NaN with a specific placeholder
    df_cleaned['features_processed'] = df_cleaned['features'].astype(str).fillna('NaN_Feature_Placeholder')

    # Process original NaN values: If 'features' was NaN, set parking, elevator, storage to -1
    # The placeholder helps identify original NaNs after conversion to string
    missing_feature_mask = df_cleaned['features_processed'] == 'NaN_Feature_Placeholder'
    df_cleaned.loc[missing_feature_mask, ['parking', 'elevator', 'storage']] = -1

    # Process 'parking'
    df_cleaned.loc[df_cleaned['features_processed'].str.contains('پارکینگ', case=False, na=False), 'parking'] = 1
    df_cleaned.loc[df_cleaned['features_processed'].str.contains('پارکینگ ندارد', case=False, na=False), 'parking'] = 0

    # Process 'elevator'
    df_cleaned.loc[df_cleaned['features_processed'].str.contains('آسانسور', case=False, na=False), 'elevator'] = 1
    df_cleaned.loc[df_cleaned['features_processed'].str.contains('آسانسور ندارد', case=False, na=False), 'elevator'] = 0

    # Process 'storage'
    df_cleaned.loc[df_cleaned['features_processed'].str.contains('انباری', case=False, na=False), 'storage'] = 1
    df_cleaned.loc[df_cleaned['features_processed'].str.contains('انباری ندارد', case=False, na=False), 'storage'] = 0

    # Drop the temporary processed features column
    df_cleaned = df_cleaned.drop(columns=['features_processed'])

    print("DataFrame after extracting and one-hot encoding features:")
    display(df_cleaned[['parking', 'elevator', 'storage']].head())
else:
    print("Warning: 'features' column not found in df_cleaned. Skipping feature extraction.")

DataFrame after extracting and one-hot encoding features:

    parking  elevator  storage
16        1         1        1
21        1         1        1
29        1         0        1
31        1         0        1
35        1         1        1

### Extract material data

In [ ]:
# Create new columns for the requested features and initialize to 'unknown'
df_cleaned['cabinet_type'] = 'unknown'
df_cleaned['floor_type'] = 'unknown'
df_cleaned['wall_type'] = 'unknown'

# Ensure 'description_processed' column exists for later cells.
# Crucially, we do this BEFORE any drops of the 'description' column.
if 'description' in df_cleaned.columns:
    df_cleaned['description_processed'] = df_cleaned['description'].astype(str).fillna('')
else:
    df_cleaned['description_processed'] = pd.Series([''] * len(df_cleaned), index=df_cleaned.index)

# Define keyword mappings
cabinet_keywords = {
    'mdf': ['ام دی اف', 'MDF', 'mdf', 'آم دی اف'],
    'high_glass': ['های گلاس', 'هایگلاس', 'هایگلس'],
    'metal': ['فلز', 'فلزی'],
    'galvanized': ['گالوانیزه', 'گالوانیز'],
    'aluminum': ['آلومینیوم', 'آلمینیوم', 'الومینیوم']
}

floor_keywords = {'ceramic': ['سرامیک'], 'parquet': ['پارکت']}
wall_keywords = {'plaster': ['گچ', 'گچی'], 'wallpaper': ['کاغذ دیواری']}

def extract_feature_type(df, feature_col, processed_col, keyword_map):
    for type_name, keywords in keyword_map.items():
        pattern = '|'.join([f'{k}' for k in keywords])
        df.loc[df[processed_col].astype(str).str.contains(pattern, case=False, na=False) & (df[feature_col] == 'unknown'), feature_col] = type_name
    return df

# Apply extraction
df_cleaned = extract_feature_type(df_cleaned, 'cabinet_type', 'description_processed', cabinet_keywords)
df_cleaned = extract_feature_type(df_cleaned, 'floor_type', 'description_processed', floor_keywords)
df_cleaned = extract_feature_type(df_cleaned, 'wall_type', 'description_processed', wall_keywords)

print("Material features extracted. 'description_processed' initialized.")

Material features extracted. 'description_processed' initialized.

### Extract additional features

In [ ]:
import pandas as pd

# Create new columns for the requested features and initialize to -1 (unknown) for binary, 'unknown' for categorical
df_cleaned['cooler_type'] = 'unknown'
df_cleaned['has_yard'] = -1
df_cleaned['has_balcony'] = -1
df_cleaned['has_cctv'] = -1
df_cleaned['has_kanaf_ceiling'] = -1
df_cleaned['has_double_glazed_windows'] = -1
df_cleaned['near_mosque_school'] = -1

# Ensure 'description_processed' column exists and fill NaN with an empty string
# This ensures that `str.contains` can be safely used without errors for all rows
if 'description' in df_cleaned.columns:
    df_cleaned['description_processed'] = df_cleaned['description'].astype(str).fillna('')
else:
    df_cleaned['description_processed'] = pd.Series([''] * len(df_cleaned), index=df_cleaned.index)

# Define keyword mappings for categorical features
cooler_keywords = {
    'split_ac': ['کولر گازی', 'اسپیلت', 'اسپلیت'],
    'evaporative_cooler': ['کولر آبی', 'آبی']
}

# Apply extraction for categorical features using the function defined earlier
df_cleaned = extract_feature_type(df_cleaned, 'cooler_type', 'description_processed', cooler_keywords)

# Apply extraction for binary features (set to 1 if positive keyword is found, 0 if negative keyword is found)
# If neither positive nor negative keyword is found, the feature remains -1 (unknown) for now.

# has_yard
df_cleaned.loc[df_cleaned['description_processed'].str.contains('حیاط|حیات', case=False, na=False), 'has_yard'] = 1
df_cleaned.loc[df_cleaned['description_processed'].str.contains('بدون حیاط', case=False, na=False), 'has_yard'] = 0 # Example negative keyword

# has_balcony
df_cleaned.loc[df_cleaned['description_processed'].str.contains('بالکن|تراس', case=False, na=False), 'has_balcony'] = 1
df_cleaned.loc[df_cleaned['description_processed'].str.contains('بدون بالکن', case=False, na=False), 'has_balcony'] = 0 # Example negative keyword

# has_cctv
df_cleaned.loc[df_cleaned['description_processed'].str.contains('دوربین', case=False, na=False), 'has_cctv'] = 1
df_cleaned.loc[df_cleaned['description_processed'].str.contains('بدون دوربین', case=False, na=False), 'has_cctv'] = 0 # Example negative keyword

# has_kanaf_ceiling
df_cleaned.loc[df_cleaned['description_processed'].str.contains('کناف|سقف کاذب', case=False, na=False), 'has_kanaf_ceiling'] = 1
df_cleaned.loc[df_cleaned['description_processed'].str.contains('بدون کناف|سقف ساده', case=False, na=False), 'has_kanaf_ceiling'] = 0 # Example negative keyword

# has_double_glazed_windows
df_cleaned.loc[df_cleaned['description_processed'].str.contains('شیشه دوجداره|دوجداره', case=False, na=False), 'has_double_glazed_windows'] = 1
df_cleaned.loc[df_cleaned['description_processed'].str.contains('بدون شیشه دوجداره', case=False, na=False), 'has_double_glazed_windows'] = 0 # Example negative keyword

# near_mosque_school
df_cleaned.loc[df_cleaned['description_processed'].str.contains('مسجد|مدرسه', case=False, na=False), 'near_mosque_school'] = 1
df_cleaned.loc[df_cleaned['description_processed'].str.contains('دور از مسجد|دور از مدرسه', case=False, na=False), 'near_mosque_school'] = 0 # Example negative keyword

# Condition features logic for property age status
df_cleaned['property_age_status'] = -1 # Initialize to -1 for unknown
df_cleaned.loc[df_cleaned['description_processed'].str.contains('نوساز|تازه ساخت', case=False, na=False), 'property_age_status'] = 1
df_cleaned.loc[df_cleaned['description_processed'].str.contains('قدیمی ساز|کلنگی', case=False, na=False), 'property_age_status'] = 0

# Post-processing: Convert remaining -1 (unknown) in binary features to 0 (does not exist)
binary_features_to_convert = [
    'has_yard', 'has_balcony', 'has_cctv', 'has_kanaf_ceiling',
    'has_double_glazed_windows', 'near_mosque_school', 'parking', 'elevator', 'storage'
] # Including parking, elevator, storage from previous cell

for col in binary_features_to_convert:
    # Only convert if the column exists and has -1 values
    if col in df_cleaned.columns:
        df_cleaned[col] = df_cleaned[col].replace(-1, 0)

# Also convert property_age_status -1 to 0 if not explicitly defined
df_cleaned['property_age_status'] = df_cleaned['property_age_status'].replace(-1, 0)

print("DataFrame after extracting features and converting unknown binary states (-1) to 0.")
display(df_cleaned[binary_features_to_convert + ['property_age_status']].head(10))

DataFrame after extracting features and converting unknown binary states (-1) to 0.

,has_yard,has_balcony,has_cctv,has_kanaf_ceiling,has_double_glazed_windows,near_mosque_school,parking,elevator,storage,property_age_status
16,0,0,0,0,0,0,1,1,1,0
21,0,0,0,0,0,0,1,1,1,0
29,0,0,0,0,0,0,1,0,1,0
31,0,0,0,0,0,1,1,0,1,0
35,0,0,0,0,0,0,1,1,1,0
41,0,0,0,0,0,0,1,1,1,0
52,0,0,0,0,0,0,1,0,1,0
53,0,1,0,0,0,0,1,1,1,1
66,0,0,0,0,0,0,1,1,1,0
70,1,0,0,0,0,0,1,1,1,0

### Extract raw

In [ ]:
import pandas as pd

# Initialize new feature columns to 0
df_cleaned['is_raw'] = 0

# Define keywords for each new feature
raw_keywords = ['خام', 'خشک کار']

# Combine keywords into regex patterns
raw_pattern = '|'.join(raw_keywords)

# Set feature to 1 if any of its keywords are found in 'description_processed'
# description_processed is ensured to exist by cell FCihXoN2UyCv
df_cleaned.loc[df_cleaned['description_processed'].str.contains(raw_pattern, case=False, na=False), 'is_raw'] = 1

## TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import hstack

# Initialize TfidfVectorizer for title
# You might want to tune parameters like max_features, min_df, max_df, ngram_range
tfidf_vectorizer_title = TfidfVectorizer(max_features=300, ngram_range=(1, 2), stop_words=None, min_df=5, max_df=0.85)

# Fit and transform the 'title' column
# Ensure 'title' is treated as string and NaNs are handled (e.g., filled with empty string)
tfidf_matrix_title = tfidf_vectorizer_title.fit_transform(df_cleaned['title'].fillna(''))

print(f"TF-IDF matrix for title shape: {tfidf_matrix_title.shape}")
print(f"Number of TF-IDF features for title: {len(tfidf_vectorizer_title.get_feature_names_out())}")

TF-IDF matrix for title shape: (3753, 300)
Number of TF-IDF features for title: 300

### Extract location

In [ ]:
import re

def extract_location_levels(location_text):
    if pd.isna(location_text) or not isinstance(location_text, str):
        return None, None

    # Find the part after 'در ' (in) which typically precedes the location info
    match = re.search(r'در\s*(.*)', location_text)
    if match:
        location_parts_str = match.group(1).strip()
        # Split by common delimiters like comma or '،'
        location_levels = [part.strip() for part in re.split(r'[،,]', location_parts_str) if part.strip()]

        level1 = location_levels[0] if len(location_levels) > 0 else None
        level2 = location_levels[1] if len(location_levels) > 1 else None
        return level1, level2
    return None, None

# Apply the function to the 'location' column
df_cleaned[['city', 'district']] = df_cleaned['location'].apply(lambda x: pd.Series(extract_location_levels(x)))

# Convert 'city' and 'district' to categorical type for LightGBM
df_cleaned['city'] = df_cleaned['city'].astype('category')
df_cleaned['district'] = df_cleaned['district'].astype('category')

print("Extracted location levels:")
display(df_cleaned[['location', 'city', 'district']].head())

Extracted location levels:

,location,city,district
16,۷ هفته پیش در برخوار، بلوار هما,برخوار,بلوار هما
21,۴ روز پیش در فولادشهر، مسکن مهر فولادشهر، بلوا...,فولادشهر,مسکن مهر فولادشهر
29,۲ روز پیش در شاهین‌شهر، خبرنگار، خ بهشتی,شاهین‌شهر,خبرنگار
31,۲ روز پیش در فولادشهر، C4، میدان ولیعصر,فولادشهر,C4
35,۲ روز پیش در شاهین‌شهر، فردوسی، خ فردوسی,شاهین‌شهر,فردوسی

In [ ]:
print("Distribution of 'district' feature:")
display(df_cleaned['district'].value_counts())

print(f"\nNumber of unique districts: {df_cleaned['district'].nunique()}")

Distribution of 'district' feature:

district
مسکن مهر فولادشهر    392
عطار                 365
خانه کارگر           291
طالقانی              150
فردوسی               146
                    ...
خ سلمان                1
خ سلام                 1
خ ستایش غربی           1
خ ستاره پنجم           1
خ ستاره هفتم           1
Name: count, Length: 568, dtype: int64

Number of unique districts: 568

In [ ]:
district_counts = df_cleaned['district'].value_counts()

# Define bins for district counts
bins = [0, 10, 20, 50, 100, 200, 300, 400]
labels = ['0-10', '11-20', '21-50', '51-100', '101-200', '201-300', '301-400']

# Group districts into these bins
district_count_groups = pd.cut(district_counts, bins=bins, labels=labels, right=True)

print("Number of districts in each count group:")
display(district_count_groups.value_counts().sort_index())

Number of districts in each count group:

count
0-10       523
11-20       19
21-50       12
51-100       7
101-200      4
201-300      1
301-400      2
Name: count, dtype: int64

## Data Cleaning - Dropping Redundant Columns

Drop unwanted features column

In [ ]:
# Only drop 'features' here, keep 'description' as it was used for description_processed
df_cleaned = df_cleaned.drop(columns=['features'], errors='ignore')
print("DataFrame after dropping the 'features' column (retaining description for later processing):")
display(df_cleaned.head())

DataFrame after dropping the 'features' column (retaining description for later processing):

,title,location,category,description,area,builded_date,rooms,land_area,total_price,price_per_meter,...,has_yard,has_balcony,has_cctv,has_kanaf_ceiling,has_double_glazed_windows,near_mosque_school,property_age_status,is_raw,city,district
16,آپارتمان۳ طبقه،سیمرغ، خرزوق (سقف ستون),۷ هفته پیش در برخوار، بلوار هما,املاک > فروش مسکونی > فروش آپارتمان > آپارتمان...,سلام و عرض ادب \nفروش آپارتمان ۳ طبقه به صورت ...,300.0,1404.0,4.0,NaN,5.800000e+09,19333000.0,...,0,0,0,0,0,0,0,0,برخوار,بلوار هما
21,فروش آپارتمان مسکن مهر ای 5,۴ روز پیش در فولادشهر، مسکن مهر فولادشهر، بلوا...,املاک > فروش مسکونی > فروش آپارتمان > فروش آپا...,درود \nفروش آپارتمان مسکن مهر محله ای 5 طبقه 4...,88.0,1403.0,2.0,NaN,2.400000e+09,27272000.0,...,0,0,0,0,0,0,0,0,فولادشهر,مسکن مهر فولادشهر
29,۱۲۰ متری / رو ب آفتاب / مخابرات,۲ روز پیش در شاهین‌شهر، خبرنگار، خ بهشتی,املاک > فروش مسکونی > فروش آپارتمان > ۱۲۰ متری...,۱۲۰ متر ✅ \n۲ خواب✅\nرو ب آفتاب✅\nکف پارکت✅\nک...,120.0,1389.0,2.0,NaN,5.300000e+09,44166000.0,...,0,0,0,0,0,0,0,0,شاهین‌شهر,خبرنگار
31,آپارتمان ۹۷ متری محله سی۴,۲ روز پیش در فولادشهر، C4، میدان ولیعصر,املاک > فروش مسکونی > فروش آپارتمان > آپارتمان...,خالق هستی \n⭐️مشاور املاک دانیال حسن پور\n✅️فو...,97.0,1393.0,2.0,NaN,4.350000e+09,44845000.0,...,0,0,0,0,0,1,0,0,فولادشهر,C4
35,آپارتمان ۱۲۳ متری فردوسی ۳ خواب,۲ روز پیش در شاهین‌شهر، فردوسی، خ فردوسی,املاک > فروش مسکونی > فروش آپارتمان > آپارتمان...,✅آپارتمان \n✅خیابان فردوسی فرعی های شرقی \n✅مج...,123.0,1395.0,3.0,NaN,7.500000e+09,60975000.0,...,0,0,0,0,0,0,0,0,شاهین‌شهر,فردوسی

## Feature Engineering - Calculating Building Age

Calculate age of building

In [ ]:
!pip install jdatetime
import jdatetime

current_shamsi_year = jdatetime.date.today().year
print(f"Current Shamsi Year: {current_shamsi_year}")
df_cleaned["age"] = current_shamsi_year - df_cleaned["builded_date"]
df_cleaned = df_cleaned.drop(columns=['builded_date'])
df_cleaned.head()

Requirement already satisfied: jdatetime in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: jalali-core>=1.0 in /usr/local/lib/python3.12/dist-packages (from jdatetime) (1.0.0)
Current Shamsi Year: 1405

,title,location,category,description,area,rooms,land_area,total_price,price_per_meter,deposit,...,has_balcony,has_cctv,has_kanaf_ceiling,has_double_glazed_windows,near_mosque_school,property_age_status,is_raw,city,district,age
16,آپارتمان۳ طبقه،سیمرغ، خرزوق (سقف ستون),۷ هفته پیش در برخوار، بلوار هما,املاک > فروش مسکونی > فروش آپارتمان > آپارتمان...,سلام و عرض ادب \nفروش آپارتمان ۳ طبقه به صورت ...,300.0,4.0,NaN,5.800000e+09,19333000.0,NaN,...,0,0,0,0,0,0,0,برخوار,بلوار هما,1.0
21,فروش آپارتمان مسکن مهر ای 5,۴ روز پیش در فولادشهر، مسکن مهر فولادشهر، بلوا...,املاک > فروش مسکونی > فروش آپارتمان > فروش آپا...,درود \nفروش آپارتمان مسکن مهر محله ای 5 طبقه 4...,88.0,2.0,NaN,2.400000e+09,27272000.0,NaN,...,0,0,0,0,0,0,0,فولادشهر,مسکن مهر فولادشهر,2.0
29,۱۲۰ متری / رو ب آفتاب / مخابرات,۲ روز پیش در شاهین‌شهر، خبرنگار، خ بهشتی,املاک > فروش مسکونی > فروش آپارتمان > ۱۲۰ متری...,۱۲۰ متر ✅ \n۲ خواب✅\nرو ب آفتاب✅\nکف پارکت✅\nک...,120.0,2.0,NaN,5.300000e+09,44166000.0,NaN,...,0,0,0,0,0,0,0,شاهین‌شهر,خبرنگار,16.0
31,آپارتمان ۹۷ متری محله سی۴,۲ روز پیش در فولادشهر، C4، میدان ولیعصر,املاک > فروش مسکونی > فروش آپارتمان > آپارتمان...,خالق هستی \n⭐️مشاور املاک دانیال حسن پور\n✅️فو...,97.0,2.0,NaN,4.350000e+09,44845000.0,NaN,...,0,0,0,0,1,0,0,فولادشهر,C4,12.0
35,آپارتمان ۱۲۳ متری فردوسی ۳ خواب,۲ روز پیش در شاهین‌شهر، فردوسی، خ فردوسی,املاک > فروش مسکونی > فروش آپارتمان > آپارتمان...,✅آپارتمان \n✅خیابان فردوسی فرعی های شرقی \n✅مج...,123.0,3.0,NaN,7.500000e+09,60975000.0,NaN,...,0,0,0,0,0,0,0,شاهین‌شهر,فردوسی,10.0

## Remove additional data

### Remove not completed apartments

In [ ]:
import pandas as pd

# Define the keywords for filtering
keywords_to_filter = ['قسطی', 'اقساط', 'سفتکاری', 'قسط', 'امتیاز']

# Create a regex pattern to search for any of the keywords
pattern = '|'.join(keywords_to_filter)

# Ensure 'description_processed' exists and handle potential NaNs by filling with an empty string
if 'description_processed' not in df_cleaned.columns:
    print("Warning: 'description_processed' column not found. Cannot filter based on keywords.")
else:
    initial_rows = len(df_cleaned)

    # Create a mask for rows to be removed
    # Use .astype(str) to ensure .str.contains works correctly even if column might have non-string types
    # na=False treats NaN values as not containing the pattern
    rows_to_remove_mask = df_cleaned['description_processed'].astype(str).str.contains(pattern, case=False, na=False)

    # Filter the DataFrame, keeping only rows that do NOT contain the keywords
    df_cleaned = df_cleaned[~rows_to_remove_mask].copy()

    removed_rows = initial_rows - len(df_cleaned)

    print(f"Number of rows before filtering: {initial_rows}")
    print(f"Number of rows containing keywords and removed: {removed_rows}")
    print(f"Number of rows after filtering: {len(df_cleaned)}")

    print("\nFirst 5 rows of the DataFrame after filtering:")
    display(df_cleaned.head())

Number of rows before filtering: 3753
Number of rows containing keywords and removed: 176
Number of rows after filtering: 3577

First 5 rows of the DataFrame after filtering:

,title,location,category,description,area,rooms,land_area,total_price,price_per_meter,deposit,...,has_balcony,has_cctv,has_kanaf_ceiling,has_double_glazed_windows,near_mosque_school,property_age_status,is_raw,city,district,age
16,آپارتمان۳ طبقه،سیمرغ، خرزوق (سقف ستون),۷ هفته پیش در برخوار، بلوار هما,املاک > فروش مسکونی > فروش آپارتمان > آپارتمان...,سلام و عرض ادب \nفروش آپارتمان ۳ طبقه به صورت ...,300.0,4.0,NaN,5.800000e+09,19333000.0,NaN,...,0,0,0,0,0,0,0,برخوار,بلوار هما,1.0
21,فروش آپارتمان مسکن مهر ای 5,۴ روز پیش در فولادشهر، مسکن مهر فولادشهر، بلوا...,املاک > فروش مسکونی > فروش آپارتمان > فروش آپا...,درود \nفروش آپارتمان مسکن مهر محله ای 5 طبقه 4...,88.0,2.0,NaN,2.400000e+09,27272000.0,NaN,...,0,0,0,0,0,0,0,فولادشهر,مسکن مهر فولادشهر,2.0
29,۱۲۰ متری / رو ب آفتاب / مخابرات,۲ روز پیش در شاهین‌شهر، خبرنگار، خ بهشتی,املاک > فروش مسکونی > فروش آپارتمان > ۱۲۰ متری...,۱۲۰ متر ✅ \n۲ خواب✅\nرو ب آفتاب✅\nکف پارکت✅\nک...,120.0,2.0,NaN,5.300000e+09,44166000.0,NaN,...,0,0,0,0,0,0,0,شاهین‌شهر,خبرنگار,16.0
31,آپارتمان ۹۷ متری محله سی۴,۲ روز پیش در فولادشهر، C4، میدان ولیعصر,املاک > فروش مسکونی > فروش آپارتمان > آپارتمان...,خالق هستی \n⭐️مشاور املاک دانیال حسن پور\n✅️فو...,97.0,2.0,NaN,4.350000e+09,44845000.0,NaN,...,0,0,0,0,1,0,0,فولادشهر,C4,12.0
35,آپارتمان ۱۲۳ متری فردوسی ۳ خواب,۲ روز پیش در شاهین‌شهر، فردوسی، خ فردوسی,املاک > فروش مسکونی > فروش آپارتمان > آپارتمان...,✅آپارتمان \n✅خیابان فردوسی فرعی های شرقی \n✅مج...,123.0,3.0,NaN,7.500000e+09,60975000.0,NaN,...,0,0,0,0,0,0,0,شاهین‌شهر,فردوسی,10.0

### Drop addition cols

In [ ]:
# Final cleanup of temporary and unwanted columns
# We drop 'description' here, but 'description_processed' will be dropped later after TF-IDF.
df_cleaned = df_cleaned.drop(columns=[
    'category',
    'apartment',
    'floor_missing',
    'rooms_missing',
    'land_area',
    'price_per_meter',
    'monthly_rent',
    'deposit',
    'deposit_and_rent_type',
    'is_new',
    'is_old',
    'location',
    'structure_only',
    'unfinished'
], errors='ignore')

# Convert to 'category' dtype for LightGBM
for col in ['cabinet_type', 'floor_type', 'wall_type', 'cooler_type']:
    if col in df_cleaned.columns:
        df_cleaned[col] = df_cleaned[col].astype('category')

print("DataFrame cleaned and categorical types set.")
display(df_cleaned.head())
print(df_cleaned.shape)

DataFrame cleaned and categorical types set.

,title,description,area,rooms,total_price,floor,parking,elevator,storage,cabinet_type,...,has_balcony,has_cctv,has_kanaf_ceiling,has_double_glazed_windows,near_mosque_school,property_age_status,is_raw,city,district,age
16,آپارتمان۳ طبقه،سیمرغ، خرزوق (سقف ستون),سلام و عرض ادب \nفروش آپارتمان ۳ طبقه به صورت ...,300.0,4.0,5.800000e+09,33.0,1,1,1,unknown,...,0,0,0,0,0,0,0,برخوار,بلوار هما,1.0
21,فروش آپارتمان مسکن مهر ای 5,درود \nفروش آپارتمان مسکن مهر محله ای 5 طبقه 4...,88.0,2.0,2.400000e+09,4.0,1,1,1,unknown,...,0,0,0,0,0,0,0,فولادشهر,مسکن مهر فولادشهر,2.0
29,۱۲۰ متری / رو ب آفتاب / مخابرات,۱۲۰ متر ✅ \n۲ خواب✅\nرو ب آفتاب✅\nکف پارکت✅\nک...,120.0,2.0,5.300000e+09,1.0,1,0,1,mdf,...,0,0,0,0,0,0,0,شاهین‌شهر,خبرنگار,16.0
31,آپارتمان ۹۷ متری محله سی۴,خالق هستی \n⭐️مشاور املاک دانیال حسن پور\n✅️فو...,97.0,2.0,4.350000e+09,3.0,1,0,1,mdf,...,0,0,0,0,1,0,0,فولادشهر,C4,12.0
35,آپارتمان ۱۲۳ متری فردوسی ۳ خواب,✅آپارتمان \n✅خیابان فردوسی فرعی های شرقی \n✅مج...,123.0,3.0,7.500000e+09,124.0,1,1,1,unknown,...,0,0,0,0,0,0,0,شاهین‌شهر,فردوسی,10.0

(3577, 25)

In [ ]:
df_cleaned.head()

,title,description,area,rooms,total_price,floor,parking,elevator,storage,cabinet_type,...,has_balcony,has_cctv,has_kanaf_ceiling,has_double_glazed_windows,near_mosque_school,property_age_status,is_raw,city,district,age
16,آپارتمان۳ طبقه،سیمرغ، خرزوق (سقف ستون),سلام و عرض ادب \nفروش آپارتمان ۳ طبقه به صورت ...,300.0,4.0,5.800000e+09,33.0,1,1,1,unknown,...,0,0,0,0,0,0,0,برخوار,بلوار هما,1.0
21,فروش آپارتمان مسکن مهر ای 5,درود \nفروش آپارتمان مسکن مهر محله ای 5 طبقه 4...,88.0,2.0,2.400000e+09,4.0,1,1,1,unknown,...,0,0,0,0,0,0,0,فولادشهر,مسکن مهر فولادشهر,2.0
29,۱۲۰ متری / رو ب آفتاب / مخابرات,۱۲۰ متر ✅ \n۲ خواب✅\nرو ب آفتاب✅\nکف پارکت✅\nک...,120.0,2.0,5.300000e+09,1.0,1,0,1,mdf,...,0,0,0,0,0,0,0,شاهین‌شهر,خبرنگار,16.0
31,آپارتمان ۹۷ متری محله سی۴,خالق هستی \n⭐️مشاور املاک دانیال حسن پور\n✅️فو...,97.0,2.0,4.350000e+09,3.0,1,0,1,mdf,...,0,0,0,0,1,0,0,فولادشهر,C4,12.0
35,آپارتمان ۱۲۳ متری فردوسی ۳ خواب,✅آپارتمان \n✅خیابان فردوسی فرعی های شرقی \n✅مج...,123.0,3.0,7.500000e+09,124.0,1,1,1,unknown,...,0,0,0,0,0,0,0,شاهین‌شهر,فردوسی,10.0

### Remove outliers data IQR

In [ ]:
import numpy as np
import pandas as pd

# 1. Initial count for percentage calculation
initial_count = len(df_cleaned)

# Define bounds
price_min = 1.0e+08
price_max = 1.0e+13
area_max = 500
age_max = 100
floor_max_filter = 15.0 # Changed to filter threshold

# Build the initial filtering condition components
filter_conditions = [
    (df_cleaned['total_price'] >= price_min),
    (df_cleaned['total_price'] <= price_max),
    (df_cleaned['age'] <= age_max),
    (df_cleaned['area'] <= area_max)
]

# Add floor filter conditionally, if 'floor' column exists
if 'floor' in df_cleaned.columns:
    # Now filtering for floor values up to floor_max_filter
    filter_conditions.append(df_cleaned['floor'] <= floor_max_filter)
    filter_conditions.append(df_cleaned['floor'] >= -1) # Keep -1 for missing or basement floors
else:
    print("Warning: 'floor' column not found in df_cleaned. Skipping initial floor filter.")

# Combine all filter conditions
initial_filter = pd.Series(True, index=df_cleaned.index)
for cond in filter_conditions:
    initial_filter = initial_filter & cond

df_filtered = df_cleaned[initial_filter].copy()

# 2. Log Transformation
df_filtered['log_total_price'] = np.log1p(df_filtered['total_price'])

# 3. IQR-based Outlier Removal for Log Price
Q1_price = df_filtered['log_total_price'].quantile(0.25)
Q3_price = df_filtered['log_total_price'].quantile(0.75)
IQR_price = Q3_price - Q1_price
lower_bound_price = Q1_price - 1.5 * IQR_price
upper_bound_price = Q3_price + 1.5 * IQR_price

df_filtered = df_filtered[(df_filtered['log_total_price'] >= lower_bound_price) &
                         (df_filtered['log_total_price'] <= upper_bound_price)].copy()

# 4. No separate clipping for Floor as it's now filtered earlier

# 5. Calculate Filtering Statistics
# These statistics will now reflect rows removed by initial hard bounds and log_total_price IQR,
# but not by floor outliers, as they are clipped instead of removed.
final_count = len(df_filtered)
removed_count = initial_count - final_count
removed_percentage = (removed_count / initial_count) * 100

print(f"Initial data points: {initial_count}")
print(f"Data points after filtering (price, age, area, and floor): {final_count}")
print(f"Total rows removed by filtering: {removed_count}")
print(f"Percentage of rows removed by filtering: {removed_percentage:.2f}%")

df_filtered = df_filtered.drop(columns=['total_price'], errors='ignore')

# 6. Correlation Prep
df_corr_prep = df_filtered.copy()
material_categorical_cols = ['cabinet_type', 'floor_type', 'wall_type', 'cooler_type']
df_corr_prep = pd.get_dummies(df_corr_prep, columns=[c for c in material_categorical_cols if c in df_corr_prep.columns], dtype=int)

# 7. Calculate correlations
features_to_corr = ['rooms', 'floor', 'area', 'age', 'parking', 'elevator', 'storage',
                    'has_yard', 'has_balcony', 'has_cctv', 'has_kanaf_ceiling',
                    'has_double_glazed_windows', 'near_mosque_school', 'property_age_status',
                    'is_raw'] # Added new features

ohe_cols = [col for col in df_corr_prep.columns if any(col.startswith(f'{prefix}_') for prefix in material_categorical_cols)]
all_features_for_corr = [f for f in features_to_corr if f in df_corr_prep.columns] + ohe_cols + ['log_total_price']

new_corr = df_corr_prep[all_features_for_corr].corr()['log_total_price'].sort_values(ascending=False)
print("\nCorrelations with log_total_price:")
print(new_corr)

Initial data points: 3577
Data points after filtering (price, age, area, and floor): 2577
Total rows removed by filtering: 1000
Percentage of rows removed by filtering: 27.96%

Correlations with log_total_price:
log_total_price                   1.000000
area                              0.621741
rooms                             0.605433
parking                           0.342782
storage                           0.203042
elevator                          0.199102
cabinet_type_high_glass           0.143821
cooler_type_split_ac              0.142042
property_age_status               0.087961
has_yard                          0.076721
wall_type_unknown                 0.065091
has_balcony                       0.062552
floor_type_parquet                0.046622
floor_type_ceramic                0.035085
floor                             0.028565
cabinet_type_unknown              0.027252
cabinet_type_aluminum             0.010476
wall_type_plaster                -0.000544
has_double_glazed_windows        -0.018711
has_kanaf_ceiling                -0.019175
cooler_type_evaporative_cooler   -0.038145
is_raw                           -0.039101
floor_type_unknown               -0.049547
wall_type_wallpaper              -0.067007
cooler_type_unknown              -0.069904
cabinet_type_metal               -0.092412
has_cctv                         -0.092879
cabinet_type_mdf                 -0.137778
near_mosque_school               -0.146281
age                              -0.453935
Name: log_total_price, dtype: float64

## Split dataframe

In [ ]:
!pip install category-encoders

Collecting category-encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category-encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category-encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category-encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category-encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category-encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category-encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category-encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category-encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category-encoders) (2026.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category-encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category-encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category-encoders) (26.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category-encoders) (1.17.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.9/85.9 kB 3.1 MB/s eta 0:00:00
Installing collected packages: category-encoders
Successfully installed category-encoders-2.9.0

In [ ]:
import torch
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from category_encoders import TargetEncoder
from sklearn.feature_extraction.text import TfidfVectorizer # Import TfidfVectorizer

# Create combined feature: city and district
df_filtered['city_district'] = df_filtered['city'].astype(str) + '_' + df_filtered['district'].astype(str)

# Define features
# Removed 'city' and 'district' as standalone features, added 'city_district'
categorical_features_cols = ['cabinet_type', 'floor_type', 'wall_type', 'cooler_type', 'property_age_status', 'city_district']
binary_features = [
    'has_yard', 'has_balcony', 'has_cctv', 'has_kanaf_ceiling',
    'has_double_glazed_windows', 'near_mosque_school',
    'parking', 'elevator', 'storage',
    'is_raw'
]
numeric_features = ['rooms', 'floor', 'area', 'age']

# Reconstruct the 'features' list to include the new combined feature
features = numeric_features + categorical_features_cols + binary_features
target = 'log_total_price'

X = df_filtered[features].copy()
y = df_filtered[target].copy()

# --- Start: Add TF-IDF features for title ---
# Ensure tfidf_vectorizer_title is available from previous cells
# Re-apply TF-IDF on the filtered DataFrame's title
tfidf_matrix_title_filtered = tfidf_vectorizer_title.transform(df_filtered['title'].fillna(''))

# Create a DataFrame from the sparse TF-IDF matrix
# Align index with df_filtered to ensure correct concatenation
tfidf_df_title_filtered = pd.DataFrame(
    tfidf_matrix_title_filtered.toarray(),
    columns=[f'tfidf_title_{col}' for col in tfidf_vectorizer_title.get_feature_names_out()],
    index=df_filtered.index # Important: Align indices
)

# Concatenate TF-IDF features to X
X = pd.concat([X, tfidf_df_title_filtered], axis=1)
# --- End: Add TF-IDF features for title ---

# --- Start: Add TF-IDF features for description ---
# Initialize TfidfVectorizer for description
tfidf_vectorizer_description = TfidfVectorizer(
    max_features=300,
    min_df=5,
    max_df=0.7,
    ngram_range=(1, 2),
    sublinear_tf=True
)

# Fit and transform the 'description_processed' column
tfidf_matrix_description = tfidf_vectorizer_description.fit_transform(df_filtered['description_processed'].fillna(''))

# Create a DataFrame from the sparse TF-IDF matrix
tfidf_df_description = pd.DataFrame(
    tfidf_matrix_description.toarray(),
    columns=[f'tfidf_description_{col}' for col in tfidf_vectorizer_description.get_feature_names_out()],
    index=df_filtered.index
)

# Concatenate TF-IDF features to X
X = pd.concat([X, tfidf_df_description], axis=1)
# --- End: Add TF-IDF features for description ---


# Reduce cardinality for 'city_district' by keeping top N and labeling others as 'rare_location'
# This replaces the previous 'district' specific cardinality reduction
if 'city_district' in X.columns:
    top_100_city_districts = X['city_district'].value_counts().nlargest(160).index
    X['city_district'] = X['city_district'].apply(lambda x: x if x in top_100_city_districts else 'rare_location')
    # Ensure 'rare_location' is also a category
    X['city_district'] = X['city_district'].astype('category')

# Convert specified categorical columns to 'category' dtype
for col in categorical_features_cols:
    X[col] = X[col].astype('category')

# Replace -1 with NaN for imputation (applied before target encoding for numerical/binary features)
cols_to_impute = numeric_features + binary_features
for col in cols_to_impute:
    X[col] = X[col].replace(-1, np.nan)

# Train-Validation-Test Split
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y.values, test_size=0.15, random_state=42) # 15% for test
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.20, random_state=42) # 20% of remaining for validation (approx 17% of total)

# Target Encoding for 'city_district'
# Removed 'city' and 'district', added 'city_district'
cols_to_target_encode = ['city_district']
te = TargetEncoder(cols=cols_to_target_encode)

# Fit and transform X_train
X_train[cols_to_target_encode] = te.fit_transform(X_train[cols_to_target_encode], y_train)
# Transform X_val and X_test
X_val[cols_to_target_encode] = te.transform(X_val[cols_to_target_encode])
X_test[cols_to_target_encode] = te.transform(X_test[cols_to_target_encode])

# Imputation for remaining NaNs (e.g., in numeric features or potential NaNs from TargetEncoder)
# This will handle NaNs in X_train, X_val, and X_test.
train_medians = X_train.median(numeric_only=True)
X_train = X_train.fillna(train_medians)
X_val = X_val.fillna(train_medians)
X_test = X_test.fillna(train_medians)

print("Data prepared.")
print("X_train shape:", X_train.shape)
print("X_val shape:", X_val.shape)
print("X_test shape:", X_test.shape)

print(f"Number of unique 'city_district' categories in full dataset (before split): {X['city_district'].nunique()}")

Data prepared.
X_train shape: (1752, 620)
X_val shape: (438, 620)
X_test shape: (387, 620)
Number of unique 'city_district' categories in full dataset (before split): 161

## Visualizing Feature Relationships with Log Total Price

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Removed the log transform for normalized_area, as it's no longer needed.

features = ['rooms', 'floor', 'area', 'parking', 'elevator', 'storage', 'age',
            'cabinet_type', 'floor_type', 'wall_type', 'cooler_type',
            'has_yard', 'has_balcony', 'has_cctv', 'has_kanaf_ceiling',
            'has_double_glazed_windows', 'near_mosque_school', 'property_age_status', 'city_district',
            'is_raw'] # Added new features and replaced 'city' with 'city_district'

plt.figure(figsize=(20, 30)) # Adjusted figure size to accommodate new features
for i, feature in enumerate(features):
    plt.subplot(8, 3, i + 1) # Adjusted subplot grid
    if feature in df_filtered.columns: # Check if feature exists
        if df_filtered[feature].dtype == 'category' or df_filtered[feature].nunique() <= 5:
            sns.boxplot(x=feature, y='log_total_price', data=df_filtered)
        else:
            sns.scatterplot(x=feature, y='log_total_price', data=df_filtered, alpha=0.6)
        plt.title(f'{feature}')
        plt.xticks(rotation=45)
    else:
        print(f"Warning: Feature '{feature}' not found in df_filtered. Skipping visualization.")

plt.tight_layout()
plt.show()

## Training with LightBGM

In [ ]:
import lightgbm as lgb
import numpy as np
from sklearn.model_selection import RepeatedKFold, cross_val_score
import pandas as pd # Ensure pandas is imported

# Define the cross-validation strategy
kf = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)

# Prepare the data for cross-validation
X_cv = pd.concat([X_train, X_val])
y_cv = np.concatenate([y_train, y_val])

# Get list of categorical features from X_cv (assuming they are now 'category' dtype)
categorical_features_for_lgbm = [col for col in X_cv.columns if X_cv[col].dtype.name == 'category']

# Initialize the LightGBM Regressor model with specified parameters
lgbm_model_cv = lgb.LGBMRegressor(objective='regression_l1',
                                  n_estimators=1000,
                                  learning_rate=0.01,
                                  num_leaves=40,
                                  random_state=42,
                                  n_jobs=-1,
                                  categorical_feature=categorical_features_for_lgbm)

print("Performing cross-validation with specified parameters...")

mse_scores = -cross_val_score(lgbm_model_cv, X_cv, y_cv.ravel(), cv=kf, scoring='neg_mean_squared_error', n_jobs=-1)
r2_scores = cross_val_score(lgbm_model_cv, X_cv, y_cv.ravel(), cv=kf, scoring='r2', n_jobs=-1)
rmse_scores = np.sqrt(mse_scores)

# 3 May 47.24%
# 6 May 45.55%
# 6 May 45.47%
# 6 May 26.62%
# 9 May 20.56%
# 10 May 19.69%
# 10 May 13.99%
# 10 May 13.94% add is_raw
# 12 May 19.50% 2k df
# 17 May 18.81% Increase districts numbers
# 20 May 19.31% add tf-idf (title)

# Evaluation on Complete Dataset:
# Mean Squared Error (MSE): 0.0338
# Root Mean Squared Error (RMSE): 0.1839
# R-squared (R2): 0.8883
# Mean Absolute Percentage Error (MAPE): 11.05%
print(f"\nCross-validation Mean MSE: {mse_scores.mean():,.4f} (+/- {mse_scores.std():,.4f})")
print(f"Cross-validation Mean RMSE: {rmse_scores.mean():,.4f} (+/- {rmse_scores.std():,.4f})")
print(f"Cross-validation Mean R-squared: {r2_scores.mean():.4f} (+/- {r2_scores.std():.4f})")

Performing cross-validation with specified parameters...

## Mean Absolute Percentage Error (MAPE)

In [ ]:
import numpy as np
import lightgbm as lgb

# 1. Train the model to ensure y_pred is available
lgbm_model = lgb.LGBMRegressor(objective='regression_l1',
                               n_estimators=1000,
                               learning_rate=0.01,
                               num_leaves=40,
                               random_state=42,
                               n_jobs=-1)

lgbm_model.fit(X_train, y_train.ravel(),
               eval_set=[(X_val, y_val.ravel())],
               callbacks=[lgb.early_stopping(100, verbose=False)])

# Generate predictions for the test set
y_pred = lgbm_model.predict(X_test)

# 2. Convert log_total_price back to original scale
actual_original_prices_test = np.expm1(y_test.flatten())
predicted_original_prices_test = np.expm1(y_pred.flatten())

# 3. Calculate MAPE
epsilon = 1e-10
absolute_percentage_errors = np.abs((actual_original_prices_test - predicted_original_prices_test) / (actual_original_prices_test + epsilon)) * 100
mean_absolute_percentage_error = np.mean(absolute_percentage_errors)

print(f"Mean Absolute Percentage Error (MAPE) on Test Set: {mean_absolute_percentage_error:.2f}%")

## Evaluate Model Performance on Specific Data Points

In [ ]:
import numpy as np
import pandas as pd

# Ensure lgbm_model is trained and y_pred is available
# If lgbm_model is not defined, train it first
if 'lgbm_model' not in locals():
    print("Training LightGBM model...")
    import lightgbm as lgb
    lgbm_model = lgb.LGBMRegressor(objective='regression_l1',
                                   n_estimators=1000,
                                   learning_rate=0.05,
                                   num_leaves=31,
                                   random_state=42,
                                   n_jobs=-1)
    lgbm_model.fit(X_train, y_train.ravel(),
                   eval_set=[(X_val, y_val.ravel())],
                   callbacks=[lgb.early_stopping(100, verbose=False)])
    y_pred = lgbm_model.predict(X_test)

# Convert y_test (log_total_price) back to original price scale for percentage calculation
actual_original_prices_test = np.expm1(y_test.flatten())

# Get predictions from the model on the test set
y_pred_original_prices_test = np.expm1(y_pred.flatten())

# Add a small epsilon to prevent division by zero for any actual_original_prices_test that might be zero
epsilon = 1e-10

# Calculate absolute percentage errors for all points
absolute_percentage_errors = np.abs((actual_original_prices_test - y_pred_original_prices_test) / (actual_original_prices_test + epsilon)) * 100

# Define a threshold for 'very significant deviations'
# Errors above this percentage will be excluded from the MAPE calculation
mape_threshold_percentage = 50.0  # You can adjust this value (e.g., 100, 200, 300)

# Filter out errors that are above the defined threshold
filtered_absolute_percentage_errors = absolute_percentage_errors[absolute_percentage_errors <= mape_threshold_percentage]

# Calculate the mean absolute percentage error for the filtered data
mean_absolute_percentage_error_filtered = np.mean(filtered_absolute_percentage_errors)

print(f"Mean Absolute Percentage Error (MAPE) on Test Set (excluding errors > {mape_threshold_percentage:.0f}%): {mean_absolute_percentage_error_filtered:.2f}%")
print(f"Number of data points excluded from Test Set: {len(absolute_percentage_errors) - len(filtered_absolute_percentage_errors)}")
print(f"Total data points considered in Test Set: {len(filtered_absolute_percentage_errors)}")
print(f"Total data points in Test Set (before exclusion): {len(absolute_percentage_errors)}")